CREATE TABLE IF NOT EXISTS livros (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(50) NOT NULL DEFAULT'',
    autor VARCHAR(50) NOT NULL DEFAULT'',
    categoria VARCHAR(50) NOT NULL DEFAULT'',
    editora VARCHAR(50) NOT NULL DEFAULT''
);

CREATE TABLE IF NOT EXISTS autor (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL DEFAULT'',
    pais VARCHAR(20) NOT NULL DEFAULT''
);

CREATE TABLE IF NOT EXISTS editora (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL DEFAULT'',
    endereco VARCHAR(50) NOT NULL DEFAULT''
);

CREATE TABLE IF NOT EXISTS categoria (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL DEFAULT'',
    descritivo VARCHAR(80) NOT NULL DEFAULT''
);

SHOW TABLES FROM biblioteca;
